projects:
  image-base-serverless-backened-api-test:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
      - components/graphql/**/*.js
      - containers/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: 6lyczhrozbd4tat7rwiuyhxwue
extensions:
  amplify:
    version: 3
